core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls", namespace="todo_list")),
]

todo_list/urls.py
from django.urls import path

from todo_list.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    toggle_complete_to_task
)


urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path(
        "tasks/<int:pk>/toggle-completed/",
        toggle_complete_to_task,
        name="toggle-complete-to-task",
    ),
]

app_name = "todo_list"

todo_list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_completed", "-created_at"]

    def __str__(self):
        return self.content

todo_list/forms.py
from django import forms

from todo_list.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={
                "type": "datetime-local",
            }
        ),
        required=False,
    )

    class Meta:
        model = Task
        fields = "__all__"

todo_list/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from todo_list.forms import TaskForm
from todo_list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task

    def get_queryset(self):
        queryset = Task.objects.prefetch_related("tags")
        return queryset


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:task-list")



class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_list:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = ["name"]
    success_url = reverse_lazy("todo_list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = ["name"]
    success_url = reverse_lazy("todo_list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list:tag-list")


def toggle_complete_to_task(request, pk):
    task = Task.objects.get(pk=pk)
    if task.is_completed:
        task.is_completed = False
        task.save()
    else:
        task.is_completed = True
        task.save()
    return HttpResponseRedirect(reverse_lazy("todo_list:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
          crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">
        
            {% block content %}{% endblock %}
        
        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo_list:task-list' %}"><b>Home</b></a></li>
  <li class="list-group-item"><a href="{% url 'todo_list:tag-list' %}"><b>Tags</b></a></li>
</ul>

templates/todo_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a href="{% url 'todo_list:tag-list' %}" class="btn btn-primary">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_list/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center mb-2 border-bottom pb-2">
    <h1><b>Tags</b></h1>
    <a href="{% url 'todo_list:tag-create' %}" class="btn btn-primary">
      <b>Add</b>
    </a>
  </div>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th><b>Name</b></th>
        <th><b>Update</b></th>
        <th><b>Delete</b></th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'todo_list:tag-update' pk=tag.pk %}" class="btn btn-secondary link-to-page">
              <b>Update</b>
            </a>
          </td>
          <td>
            <a href="{% url 'todo_list:tag-delete' pk=tag.pk %}" class="btn btn-secondary link-to-page">
              <b>Delete</b>
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags yet.</p>
    
  {% endif %}
{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a href="{% url 'todo_list:task-list' %}" class="btn btn-primary">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_list/task_list.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center mb-4">
  <h1><b>TODO list</b></h1>
    <a href="{% url 'todo_list:task-create' %}" class="btn btn-primary link-to-page">
      <b>Add task</b>
    </a>
  </div>
  {% if task_list %}
  <ul class="list-unstyled">
    {% for task in task_list %}
      <li class="pb-3 mb-3 border-bottom">
        <div class="d-flex justify-content-between align-items-start">
          <div>
            <b>{{ task.content }}</b>
            {% if task.is_completed %}
              <span class="text-success"><b>Done</b></span>
            {% else %}
              <span class="text-danger"><b>Not done</b></span>
            {% endif %}
            <br>
            <small>Created: {{ task.created_at }}</small>
            {% if task.deadline %}
              <small style="color: #800000;" class="mb-1">Deadline: {{ task.deadline }}</small>
            {% endif %}
            {% if task.tags.all %}
              <br><small>Tags:</small>
              <small>
                {% for tag in task.tags.all %}
                  <span class="badge bg-secondary me-1">{{ tag.name }}</span>
                {% endfor %}
              </small>
            {% endif %}
                <a href="{% url 'todo_list:task-update' pk=task.pk %}"><b>Update</b></a>
                <a href="{% url 'todo_list:task-delete' pk=task.pk %}"><b>Delete</b></a>
          </div>
          <div>
            {% if task.is_completed %}
              <a href="{% url 'todo_list:toggle-complete-to-task' pk=task.pk %}" class="btn btn-secondary">
                <b>Undo</b>
              </a>
            {% else %}
              <a href="{% url 'todo_list:toggle-complete-to-task' pk=task.pk %}" class="btn btn-success">
                <b>Complete</b>
              </a>
            {% endif %}
          </div>
        </div>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>There are no tasks yet.</p>
{% endif %}
{% endblock %}